name: Append Solved Problems

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest
    outputs:
      MESSAGE: ${{ steps.extract-message.outputs.MESSAGE }}
      IS_INTEGER: ${{ steps.check-integer.outputs.IS_INTEGER }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Extract commit message
        id: extract-message
        run: echo "MESSAGE=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Check if commit message is an integer
        id: check-integer
        run: |
          if [[ $MESSAGE =~ ^[0-9]+$ ]]; then
            echo "IS_INTEGER=true" >> $GITHUB_ENV
          else
            echo "IS_INTEGER=false" >> $GITHUB_ENV
          fi

  append-solved:
      needs: extract
      runs-on: ubuntu-latest
      if: needs.extract.outputs.IS_INTEGER == 'true'
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Append to solved_problems.txt
          env:
            MESSAGE: ${{ needs.extract.outputs.MESSAGE }}
          run: |
            echo $MESSAGE >> solved_problems.txt
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add solved_problems.txt
            git commit -m "Append solved_problems.txt"
            git push

  close-issue:
      needs: extract
      runs-on: ubuntu-latest
      if: needs.extract.outputs.IS_INTEGER == 'true'
      steps:
        - name: Close related GitHub issue
          env:
            MESSAGE: ${{ needs.extract.outputs.MESSAGE }}
          run: |
            issue_number=$(gh issue list --state open --search "LeetCode $MESSAGE" --json number,title \
              --jq ".[] | select(.title | test(\"LeetCode Easy $MESSAGE|LeetCode Medium $MESSAGE|LeetCode Hard $MESSAGE\")) | .number")
            if [ -n "$issue_number" ]; then
              gh issue close $issue_number --comment "Issue resolved by solving problem $MESSAGE."
            fi
