name: Append Solved Problems

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check-integer:
    runs-on: ubuntu-latest
    outputs:
      is_integer: ${{ env.is_integer }}
      message: ${{ env.message }}

    steps:
      - name: Extract commit message
        id: extract-message
        run: echo "message=$(git log -1 --pretty=%B)" >> $GITHUB_ENV

      - name: Check if commit message is an integer
        id: check-integer
        run: |
          if [[ $message =~ ^[0-9]+$ ]]; then
            echo "is_integer=true" >> $GITHUB_ENV
          else
            echo "is_integer=false" >> $GITHUB_ENV
          fi

  append-solved:
      needs: check-integer
      runs-on: ubuntu-latest
      if: ${{ env.is_integer == 'true' }}
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Append to solved_problems.txt
          env:
            MESSAGE: ${{ env.message }}
          run: |
            echo $MESSAGE >> solved_problems.txt
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add solved_problems.txt
            git commit -m "Append solved_problems.txt"
            git push

  close-issue:
      needs: check-integer
      runs-on: ubuntu-latest
      if: ${{ env.is_integer == 'true' }}
      steps:
        - name: Close related GitHub issue
          env:
            MESSAGE: ${{ env.message }}
          run: |
            issue_number=$(gh issue list --state open --search "LeetCode $MESSAGE" --json number,title \
              --jq ".[] | select(.title | test(\"LeetCode Easy $MESSAGE|LeetCode Medium $MESSAGE|LeetCode Hard $MESSAGE\")) | .number")
            if [ -n "$issue_number" ]; then
              gh issue close $issue_number --comment "Issue resolved by solving problem $MESSAGE."
            fi
