name: Fetch and Check LeetCode Daily Problem

on:
  workflow_dispatch: # Trigger manually or schedule it
  schedule:
    - cron: '5 0 * * *' # Runs daily at 0:5 UTC

jobs:
  fetch-daily-problem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1 # Perform a shallow checkout

      - name: Fetch LeetCode Daily Problem
        id: fetch_problem
        run: |
          curl -X POST https://leetcode.com/graphql \
          -H "Content-Type: application/json" \
          -d '{"query":"query questionOfToday { activeDailyCodingChallengeQuestion { date question { title titleSlug difficulty acRate questionFrontendId } } }"}' > response.json
          cat response.json

      - name: Parse Problem Details
        id: parse_problem
        run: |
          TITLE=$(jq -r '.data.activeDailyCodingChallengeQuestion.question.title' response.json)
          SLUG=$(jq -r '.data.activeDailyCodingChallengeQuestion.question.titleSlug' response.json)
          DIFFICULTY=$(jq -r '.data.activeDailyCodingChallengeQuestion.question.difficulty' response.json)
          PROBLEM_ID=$(jq -r '.data.activeDailyCodingChallengeQuestion.question.questionFrontendId' response.json)
          DATE=$(jq -r '.data.activeDailyCodingChallengeQuestion.date' response.json | sed 's/-//g') # Convert date to YYYYMMDD format
          echo "Today's LeetCode Problem: $TITLE"
          echo "Problem ID: $PROBLEM_ID"
          echo "Difficulty: $DIFFICULTY"
          echo "Date: $DATE"
          echo "Link: https://leetcode.com/problems/$SLUG/"
          # Write outputs to environment file
          echo "PROBLEM_ID=$PROBLEM_ID" >> $GITHUB_ENV
          echo "TITLE=$TITLE" >> $GITHUB_ENV
          echo "DIFFICULTY=$DIFFICULTY" >> $GITHUB_ENV
          echo "SLUG=$SLUG" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV

      - name: Check if Problem Already Solved
        id: check_solved
        run: |
          if grep -Fxq "$PROBLEM_ID" solved_problems.txt; then
            echo "STATUS=Solved" >> $GITHUB_ENV
          else
            echo "STATUS=New" >> $GITHUB_ENV
          fi

      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          script: |
            const status = process.env.STATUS;
            const title = process.env.TITLE;
            const difficulty = process.env.DIFFICULTY;
            const problemId = process.env.PROBLEM_ID;
            const slug = process.env.SLUG;
            const date = process.env.DATE;
            const issueTitle = `${date} - ${status} LeetCode ${difficulty} ${problemId} ${title}`;

            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: issueTitle,
              body: issueTitle,
            });

            console.log(`Created issue: ${issue.html_url}`);
